services:
  - type: web
    name: bugcombo-backend
    runtime: python
    buildCommand: bash build.sh
    startCommand: daphne core.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: "llama-3.3-70b-versatile"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_URL
        value: "https://bugcomboo.onrender.com"
      - key: REDIS_URL
        sync: false