# Generated by Django 6.0.6 on 2026-08-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['condition_value']},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='condition',
        ),
        migrations.AddField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(default='wins', max_length=50),
        ),
        migrations.AddField(
            model_name='achievement',
            name='condition_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
