# Generated by Django 6.0.6 on 2026-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
