# Generated by Django 6.0.6 on 2026-07-23 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0003_alter_duelroom_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelroom',
            name='code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='duelroom',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('judging', 'Judging'), ('finished', 'Finished')], db_index=True, default='waiting', max_length=10),
        ),
        migrations.AddIndex(
            model_name='duelroom',
            index=models.Index(fields=['status', 'created_at'], name='duels_duelr_status_2e538c_idx'),
        ),
        migrations.AddIndex(
            model_name='duelroom',
            index=models.Index(fields=['creator', 'status'], name='duels_duelr_creator_aaff97_idx'),
        ),
        migrations.AddIndex(
            model_name='duelroom',
            index=models.Index(fields=['opponent', 'status'], name='duels_duelr_opponen_7392a9_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['room', 'player'], name='duels_submi_room_id_f83bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['player', 'submitted_at'], name='duels_submi_player__9606ad_idx'),
        ),
    ]
