# Generated by Django 6.0.6 on 2026-08-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0004_alter_duelroom_code_alter_duelroom_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelroom',
            name='duration',
            field=models.IntegerField(choices=[(60, '1 minute'), (180, '3 minutes'), (300, '5 minutes')], default=180),
        ),
    ]
