# Generated by Django 6.0.6 on 2026-08-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0005_duelroom_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelroom',
            name='timeout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
