# Generated by Django 6.0.6 on 2026-08-16 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0006_duelroom_timeout_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duelroom',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='duelroom',
            index=models.Index(fields=['archived', 'created_at'], name='duels_duelr_archive_fc8378_idx'),
        ),
    ]
