# Generated by Django 6.0.6 on 2026-08-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='avg_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bug',
            name='times_used',
            field=models.IntegerField(default=0),
        ),
    ]
